# Generated by Django 6.0.4 on 2026-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ingest API key',
                'verbose_name_plural': 'Ingest API keys',
            },
        ),
    ]
