# Generated by Django 6.0.4 on 2026-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0002_ingestapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawcontent',
            name='status',
        ),
        migrations.AlterField(
            model_name='rawcontent',
            name='source_url',
            field=models.URLField(),
        ),
    ]
