# Generated by Django 6.0.4 on 2026-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0003_remove_rawcontent_status_alter_rawcontent_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcontent',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='rawcontent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
