# Generated by Django 6.0.4 on 2026-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0004_rawcontent_language_code_rawcontent_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmodule',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='processedmodule',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='processedmodule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
