# Generated by Django 6.0.4 on 2026-05-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0005_processedmodule_review_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(max_length=64, unique=True)),
                ('prompt_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(default='openrouter-default', max_length=100)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=50)),
                ('prompt_body', models.TextField()),
                ('prompt_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('raw_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_jobs', to='content_engine.rawcontent')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='content_eng_status_7d9c1b_idx'), models.Index(fields=['prompt_hash'], name='content_eng_prompt__eace92_idx')],
            },
        ),
    ]
