# Generated by Django 6.0.4 on 2026-05-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0007_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcontent',
            name='locale',
            field=models.CharField(blank=True, default='', help_text='Optional BCP 47 locale display hint (e.g. en-US, id-ID).', max_length=32),
        ),
    ]
