# Generated by Django 6.0.4 on 2026-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0008_rawcontent_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReplyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('route', models.CharField(max_length=32)),
                ('reply', models.TextField()),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'chat reply caches',
            },
        ),
    ]
