# Generated by Django 6.0.4 on 2026-05-10 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0009_chat_reply_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], db_index=True, default='free', max_length=16)),
                ('pro_access_until', models.DateTimeField(blank=True, help_text='UTC instant until which paid (Pro) chat quota applies; from Stripe current_period_end.', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_status', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_entitlement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'learner entitlement',
                'verbose_name_plural': 'learner entitlements',
            },
        ),
    ]
