# Generated by Django 6.0.4 on 2026-05-10 07:24

from django.db import migrations, models
from django.utils import timezone


def forwards_legacy_pro_active(apps, schema_editor):
    LearnerEntitlement = apps.get_model("content_engine", "LearnerEntitlement")
    now = timezone.now()
    for ent in LearnerEntitlement.objects.filter(plan="pro").iterator():
        if ent.pro_access_until and ent.pro_access_until > now:
            ent.payment_status = "active"
            ent.save(update_fields=["payment_status"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0010_learner_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerentitlement',
            name='payment_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending payment'), ('active', 'Active')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='learnerentitlement',
            name='pending_plan_code',
            field=models.CharField(blank=True, default='', help_text='Paket yang dipilih user; menunggu pembayaran gateway.', max_length=16),
        ),
        migrations.AlterField(
            model_name='learnerentitlement',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('go', 'Go'), ('plus', 'Plus'), ('pro', 'Pro')], db_index=True, default='free', max_length=16),
        ),
        migrations.AlterField(
            model_name='learnerentitlement',
            name='pro_access_until',
            field=models.DateTimeField(blank=True, help_text='UTC sampai langganan berlaku (diisi setelah pembayaran terverifikasi).', null=True),
        ),
        migrations.RunPython(forwards_legacy_pro_active, noop_reverse),
    ]
