# Generated by Django 6.0.4 on 2026-05-10 07:37

from django.db import migrations, models


def seed_billing_catalog(apps, schema_editor):
    BillingCatalogPlan = apps.get_model("content_engine", "BillingCatalogPlan")
    if BillingCatalogPlan.objects.exists():
        return
    rows = [
        {
            "code": "free",
            "title": "Free",
            "price_prefix": "",
            "price_idr_monthly": 0,
            "price_display_override": "",
            "period_label": "/ bulan",
            "vat_note": "",
            "slogan": "Lihat apa yang AI bisa lakukan untuk belajar.",
            "features": [
                {"icon": "spark", "text": "Model inti tutor"},
                {"icon": "message", "text": "Kuota chat harian terbatas"},
                {"icon": "book", "text": "Akses modul dasar"},
                {"icon": "memory", "text": "Memori konteks singkat"},
            ],
            "footer_note": "",
            "popular": False,
            "is_active": True,
            "sort_order": 0,
        },
        {
            "code": "go",
            "title": "Go",
            "price_prefix": "",
            "price_idr_monthly": 75_000,
            "price_display_override": "",
            "period_label": "/ bulan",
            "vat_note": "Termasuk PPN",
            "slogan": "Terus belajar dengan akses lebih luas.",
            "features": [
                {"icon": "spark", "text": "Model inti tutor"},
                {"icon": "message", "text": "Kuota chat lebih besar dari Free"},
                {"icon": "book", "text": "Akses semua modul belajar"},
                {"icon": "memory", "text": "Memori konteks lebih panjang"},
                {"icon": "search", "text": "Ringkasan materi lebih detail"},
            ],
            "footer_note": "",
            "popular": False,
            "is_active": True,
            "sort_order": 1,
        },
        {
            "code": "plus",
            "title": "Plus",
            "price_prefix": "",
            "price_idr_monthly": 349_000,
            "price_display_override": "",
            "period_label": "/ bulan",
            "vat_note": "Termasuk PPN",
            "slogan": "Buka pengalaman belajar penuh.",
            "features": [
                {"icon": "spark", "text": "Model tutor lebih mumpuni"},
                {"icon": "message", "text": "Kuota chat jauh lebih besar"},
                {"icon": "book", "text": "Konteks modul mendalam"},
                {"icon": "memory", "text": "Memori lintas sesi"},
                {"icon": "search", "text": "Eksplorasi materi diperluas"},
                {"icon": "zap", "text": "Prioritas respons lebih tinggi"},
            ],
            "footer_note": "",
            "popular": True,
            "is_active": True,
            "sort_order": 2,
        },
        {
            "code": "pro",
            "title": "Pro",
            "price_prefix": "Mulai",
            "price_idr_monthly": 1_889_000,
            "price_display_override": "",
            "period_label": "/ bulan",
            "vat_note": "Termasuk PPN",
            "slogan": "Maksimalkan produktivitas belajar.",
            "features": [
                {"icon": "stack", "text": "Semua fitur Plus, ditambah:"},
                {"icon": "message", "text": "Kuota chat sangat besar (fair usage)"},
                {"icon": "spark", "text": "Akses prioritas ke model terbaik"},
                {"icon": "memory", "text": "Konteks & memori paling panjang"},
                {"icon": "zap", "text": "Akses awal fitur eksperimental"},
            ],
            "footer_note": "Batas wajar berlaku untuk antisalahgunakan.",
            "popular": False,
            "is_active": True,
            "sort_order": 3,
        },
    ]
    for row in rows:
        BillingCatalogPlan.objects.create(**row)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0011_billing_internal_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCatalogPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('price_prefix', models.CharField(blank=True, default='', max_length=32)),
                ('price_idr_monthly', models.PositiveIntegerField(default=0)),
                ('price_display_override', models.CharField(blank=True, default='', help_text='Kosong = tampilkan nominal otomatis dari harga bulanan (format IDR).', max_length=64)),
                ('period_label', models.CharField(default='/ bulan', max_length=32)),
                ('vat_note', models.CharField(blank=True, default='', max_length=120)),
                ('slogan', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list, help_text='Daftar fitur JSON, mis. [{"icon":"spark","text":"..."}]')),
                ('footer_note', models.TextField(blank=True, default='')),
                ('popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'paket billing (katalog)',
                'verbose_name_plural': 'paket billing (katalog)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_billing_catalog, noop_reverse),
    ]
